/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        nav: "var(--nav-background)",
        "nav-foreground": "var(--nav-foreground)",
        "nav-hover": "var(--nav-hover)",
        surface: "var(--surface)",
        "surface-foreground": "var(--surface-foreground)",
        "surface-muted": "var(--surface-muted)",
        "muted-foreground": "var(--muted-foreground)",
        border: "var(--border)",
        input: "var(--input-background)",
        "input-foreground": "var(--input-foreground)",
        "input-border": "var(--input-border)",
        "input-focus": "var(--input-focus)",
        ring: "var(--ring)",
        button: "var(--button-background)",
        "button-foreground": "var(--button-foreground)",
        "button-hover": "var(--button-hover-background)",
        footer: "var(--footer-background)",
        "footer-foreground": "var(--footer-foreground)",
        tag: "var(--tag-background)",
        "tag-foreground": "var(--tag-foreground)",
        "tag-alt": "var(--tag-alt-background)",
        "tag-alt-foreground": "var(--tag-alt-foreground)",
        primary: "#FF6B6B",
        secondary: "#4ECDC4",
        accent: "#FFD166",
      },
    },
  },
  plugins: [],
}; 
